#!/bin/sh

[ -f /etc/vbox/vbox.cfg ] && . /etc/vbox/vbox.cfg

if [ -z "$SYNOPKG_PKGNAME" ]; then
    PACKAGE_NAME="virtualbox4dsm"
    PACKAGE_VER=`get_key_value "/var/packages/${PACKAGE_NAME}/INFO" "version"`
else
    PACKAGE_NAME=$SYNOPKG_PKGNAME
    PACKAGE_VER=$SYNOPKG_PKGVER
fi


DSM_CONFIG="/etc.defaults/synoinfo.conf"
PACKAGE_DIR="/var/packages/$PACKAGE_NAME"
TARGET_DIR="$PACKAGE_DIR/target"
PACKAGE_ENABLED="${PACKAGE_DIR}/enabled"
SCRIPTLOG="$TARGET_DIR/share/scripts.log"

PIDFILE="$TARGET_DIR/wolsvc.pid"
WOL="$PACKAGE_DIR/enabled_wol"


start()
{
	echo "**** Start at $(date) ****" >> "${SCRIPTLOG}" 2>&1
	# after DSM upgrade opt folder is missing, fix it
	if [ ! -d /opt/VirtualBox ]; then
			[ ! -d /opt ] && mkdir /opt
			cp -r $TARGET_DIR/opt/* /opt/
	fi

	# copy conf from share
	if [ -d $TARGET_DIR/share/.config ]; then
		cp -rf $TARGET_DIR/share/.config ${HOME}
	fi

	# load drivers
	"$TARGET_DIR/scripts/vboxdrv.sh" start >> "${SCRIPTLOG}" 2>&1
	# start vbox SOAP Service
	"$TARGET_DIR/scripts/vboxweb-service.sh" start >> "${SCRIPTLOG}" 2>&1
	# start VM's
	"$TARGET_DIR/scripts/vboxinit.sh" start >> "${SCRIPTLOG}" 2>&1
	# exec USB fix
	#"$TARGET_DIR/scripts/vbox-usb.sh" start >> "${SCRIPTLOG}" 2>&1
	# start WOL service
	"$TARGET_DIR/scripts/wol.sh" start >> "${SCRIPTLOG}" 2>&1
	echo "**** Start finished at $(date) ****" >> "${SCRIPTLOG}" 2>&1
}

stop()
{
	echo "**** Stop at $(date) ****" >> "${SCRIPTLOG}" 2>&1
	# stop services, we will let vboxdrv shutdown VM's based on vbox.cfg

	# stop WOL service
	"$TARGET_DIR/scripts/wol.sh" stop >> "${SCRIPTLOG}" 2>&1
	
	# stop VM's
	"$TARGET_DIR/scripts/vboxinit.sh" stop >> "${SCRIPTLOG}" 2>&1
	
	# stop vbox SOAP service
	"$TARGET_DIR/scripts/vboxweb-service.sh" stop >> "${SCRIPTLOG}" 2>&1
	
	# stop USB fix
	#"$TARGET_DIR/scripts/vbox-usb.sh" stop >> "${SCRIPTLOG}" 2>&1
	
	# unload drivers
	"$TARGET_DIR/scripts/vboxdrv.sh" stop >> "${SCRIPTLOG}" 2>&1

	# copy config to share
	if [ -d $TARGET_DIR/share/ ]; then
		cp -rf "${HOME}"/.config $TARGET_DIR/share/
	fi
	
	echo "**** Stop finished at $(date) ****" >> "${SCRIPTLOG}" 2>&1
}

case $1 in
   	start)
		# check enabled
		if [ ! -f "${PACKAGE_DIR}/enabled" ]; then
			exit 0;
		fi

		# start routine
		start
		exit 0
        ;;
   	stop)
		stop
       	exit 0
        ;;
	restart)
		stop && start
	;;
  	status)
		# 0: package is running.
		# 1: program of package is dead and /var/run pid file exists.
		# 2: program of package is dead and /var/lock lock file exists
		# 3: package is not running
		# 4: package status is unknown
		# 150: package is broken and should be reinstalled. 
		if [ $(ps aux | grep /opt/VirtualBox -c) == 4 ]; then 
			exit 0
		fi
		
		if [ -f "/var/run/vboxweb-service" ]; then
			exit 1
		fi
		
		if [ $(lsmod | grep vbox -c) == 4 ]; then
			exit 4
		fi
		exit 3
        ;;
	killall)
		stop
		exit 0
        ;;
	log)
		echo "$TARGET_DIR/share/vbox.log"
       	exit 0
        ;;
   	*)
		echo "Usage: start-stop-status.sh start|stop|restart|status|killall|log"
       	exit 1
        ;;
esac
